apiVersion: v1
kind: Secret
metadata:
  name: docker-pull-secret
  namespace: jenkins
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "${DOCKER_USERNAME}",
          "password": "${DOCKER_TOKEN}",
          "auth": ""
        }
      }
    }