apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: ttyd
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: "ttyd"
  OAUTH2_PROXY_CLIENT_SECRET: "${KEYCLOAK_CLIENT_SECRET}"
  OAUTH2_PROXY_COOKIE_SECRET: "${CREATED_COOKIE_SECRET}"
