apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-oss-cache-pvc
  namespace: gpt-oss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
