apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-file-server-pvc
  namespace: static-file-server
spec:
  resources:
    requests:
      storage: 30Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client