apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: insight
spec:
  version: 8.12.1
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        xpack.security.authc.anonymous.authz_exception: false
        xpack.security.authc.anonymous.roles:
          - superuser
        xpack.security.authc.anonymous.username: admin
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: nfs-client
            resources:
              requests:
                storage: 100Gi
  auth:
    fileRealm:
      - secretName: secret-user-admin
      - secretName: secret-user-news-reader
